# This workflow will install Python dependencies, run tests, lint (black), applies semantic releases and pushed to PyPi with a single version of Python

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "oopnet --check"
    - name: Test with pytest
      run: |
        pytest
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PyPI_token: ${{ secrets.PyPI_TOKEN }}
