# This workflow will install Python dependencies, run tests, lint (black), applies semantic releases and pushed to PyPi with a single version of Python

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest scoop
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: "oopnet"
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --global user.name 'OOPNET Bot'
        git config --global user.email 'oopnet-bot@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Automated changes"
        git push
#     - name: Check out my other private repo
#       uses: actions/checkout@master
#       with:
#         repository: oopnet/linux_epanet_2.2
#         token: ${{ secrets.GITHUB_TOKEN }}
#     - name: Test with pytest
#       run: |
#         pytest
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        PyPI_token: ${{ secrets.PyPI_TOKEN }}
